### ISSUE TITLE
Multiple tags on uploaded "packages"

### ISSUE THREAD

**Issue by bkje14** [AnyBody/anybody-container#1]
Can we somehow add multiple tags to uploaded images found under "Packages" ? 

It should be possible in the build cmd fx. `docker build -t <tag1> -t <tag2>`
currently it is not possible to specify the `latest` tag only the direct `7.3.4-0`

Maybe we could have the `latest` tag follow the released ams version and a `beta` tag that follows the upcoming versions beta branch? 

> Note: I could not see where the "packages" are generated so I could not suggest a change
> Is it a Github Action? - there seem to be some nice templates for automating it

**Comment by melund** [comment]
I think that should be handled now: 
![image](https://github.com/AnyBody/anybody-container/assets/1038978/4daa1742-5d41-458b-bc5f-f27bfe5665d6)
